apiVersion: v1
kind: ConfigMap
metadata:
  name: agola
  namespace: gitops
data:
  config.yml: |
    gateway:
      # The api url that clients will call
      # Change this to the exposed "agola" service IP
      apiExposedURL: "https://agola.0x76.dev"
      # The web interface url that clients will use
      # Change this to the exposed "agola" service IP
      webExposedURL: "https://agola.0x76.dev"

      runserviceURL: "http://agola-internal:4000"
      configstoreURL: "http://agola-internal:4002"
      gitserverURL: "http://agola-internal:4003"
      web:
        listenAddress: ":8000"
      tokenSigning:
        # hmac or rsa (it possible use rsa)
        method: hmac
        # key to use when signing with hmac
        key: $SIGNING_KEY
      adminToken: "$ADMIN_TOKEN"
    
    scheduler:
      runserviceURL: "http://agola-internal:4000"

    notification:
      webExposedURL: "https://agola.0x76.dev"
      runserviceURL: "http://agola-internal:4000"
      configstoreURL: "http://agola-internal:4002"
      db:
        type: postgres
        connString: "postgres://agola_notif@10.42.42.26/agola_notif?sslmode=disable"
    
    configstore:
      dataDir: /mnt/agola/local/configstore
      db:
        type: postgres
        connString: "postgres://agola_config@10.42.42.26/agola_config?sslmode=disable"
      objectStorage:
        type: s3
        endpoint: "https://o.0x76.dev"
        bucket: agola-configstore
        accessKey: $MINIO_ACCESS_KEY
        secretAccessKey: $MINIO_SECRET_ACCESS_KEY
      web:
        listenAddress: ":4002"
    
    runservice:
      #debug: true
      dataDir: /mnt/agola/local/runservice
      db:
        type: postgres
        connString: "postgres://agola_runservice@10.42.42.26/agola_runservice?sslmode=disable"
      objectStorage:
        type: s3
        endpoint: "https://o.0x76.dev"
        bucket: agola-runservice
        accessKey: $MINIO_ACCESS_KEY
        secretAccessKey: $MINIO_SECRET_ACCESS_KEY
      web:
        listenAddress: ":4000"
    
    executor:
      dataDir: /mnt/agola/local/executor
      # The directory containing the toolbox compiled for the various supported architectures
      toolboxPath: ./bin
      runserviceURL: "http://agola-internal:4000"
      web:
        listenAddress: ":4001"
      activeTasksLimit: 2
      driver:
        type: kubernetes

    gitserver:
      dataDir: /mnt/agola/local/gitserver
      gatewayURL: "http://agola-internal:8000"
      web:
        listenAddress: ":4003"
