apiVersion: apps/v1
kind: Deployment
metadata:
  name: agola
  namespace: gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agola
  template:
    metadata:
      labels:
        app: agola
    spec:
      initContainers:
        - name: config
          image: 0x76/envsubst
          args: ["sh", "-c", "cat /mnt/agola/config/config.yml | envsubst > /mnt/agola/local/config.yml"]
          volumeMounts:
            - mountPath: /mnt/agola/local
              name: agola-localdata
            - mountPath: /mnt/agola/config
              name: config-volume
          envFrom:
            - secretRef:
                name: agola
      containers:
        - name: agola
          image: 0x76/agola:edge
          command:
            - /bin/agola
            - serve
            - "--config"
            - /mnt/agola/local/config.yml
            - "--components"
            - all-base,executor
            # - "--debug"
          ports:
            - containerPort: 8000
            - containerPort: 4000
            - containerPort: 4002
            - containerPort: 4003
          volumeMounts:
            - name: config-volume
              mountPath: /mnt/agola/config
            - name: agola-localdata
              mountPath: /mnt/agola/local
      volumes:
        - name: config-volume
          configMap:
            name: agola
        - name: agola-localdata
          emptyDir: {}
