apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: zookeeper
  namespace: flux-system
spec:
  image: registry.xirion.net/library/zookeeper
  interval: 1m0s
  secretRef:
    name: xirion-registry-creds
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: zookeeper
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: zookeeper
  policy:
    semver:
      range: "*"
