kind: pipeline
type: kubernetes
name: default
steps:
  - name: yamllint
    image: registry.gitlab.com/pipeline-components/yamllint
    commands:
      - yamllint -c .yamllint.yaml .
  - name: nix flake check
    image: nixos/nix:master
    commands:
      - nix --extra-experimental-features nix-command --extra-experimental-features flakes flake prefetch
      - nix --extra-experimental-features nix-command --extra-experimental-features flakes flake check --no-build
