pipeline:
  check:
    image: nixos/nix:2.15.0
    environment:
      - NIX_CONFIG=experimental-features = nix-command flakes
    commands:
      - nix run 'nixpkgs#statix' check
      - nix run 'github:astro/deadnix' -- -f
      - nix run 'nixpkgs#yamllint' .
