pipeline:
  check:
    image: nixos/nix:2.14.1
    environment:
      - NIX_CONFIG=experimental-features = nix-command flakes
    commands:
      - nix run 'nixpkgs#statix' check
      - nix run 'nixpkgs#yamllint' .
