apiVersion: apps/v1
kind: Deployment
metadata:
  name: grist
  namespace: services
  labels:
    app: grist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grist
  template:
    metadata:
      labels:
        app: grist
    spec:
      volumes:
        - name: persist
          persistentVolumeClaim:
          claimName: grist
      containers:
        - name: grist-core
          image: gristlabs/grist:1.1.7
          volumeMounts:
            - name: persist
              mountPath: /persist
          env:
            - name: APP_HOME_URL
              value: "https://grist.0x76.dev"
            - name: GRIST_SINGLE_ORG
              value: ""
            - name: GRIST_SUPPORT_ANON
              value: false
            - name: PYTHON_VERSION
              value: 3
            - name: PYTHON_VERSION_ON_CREATION
              value: 3
            - name: GRIST_FORWARD_AUTH_HEADER
              value: X-Forwarded-User
            - name: GRIST_FORWARD_AUTH_LOGOUT_PATH
              value: /_oauth/logout
          envFrom:
            - secretRef:
                name: grist
          ports:
            - containerPort: 8484
