apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grist
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
