name: Plex Update

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update:
    runs-on: native
    steps:
      - uses: actions/checkout@v3
      - env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        run: |
          git config user.name "Forgejo Actions Bot"
          git config user.email "<>"

          # Run Update script
          ./nixos/pkgs/plex-pass/update.sh

          git add ./nixos/pkgs/plex-pass/

          # Push if changed
          if git status ./nixos/pkgs/plex-pass/ | grep -q "to be committed"; then
            git commit -m "Update Plex"
            git push origin main
          fi
