apiVersion: apps/v1
kind: Deployment
metadata:
  name: x76dev
  namespace: websites
  labels:
    app: x76dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: x76dev
  template:
    metadata:
      labels:
        app: x76dev
    spec:
      containers:
        - name: x76dev
          image: git.0x76.dev/v/0x76.dev:5
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: x76dev-service
  namespace: websites
spec:
  selector:
    app: x76dev
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: x76dev-ingress
  namespace: websites
spec:
  rules:
    - host: "0x76.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: x76dev-service
                port:
                  number: 80
