apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: websites
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: git.0x76.dev/v/blog.xirion.net:5
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: blog
  namespace: websites
spec:
  selector:
    app: blog
  ports:
    - protocol: TCP
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog
  namespace: websites
spec:
  rules:
    - host: "blog.xirion.net"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: blog
                port:
                  number: 8080
