apiVersion: apps/v1
kind: Deployment
metadata:
  name: xirion
  namespace: websites
  labels:
    app: xirion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xirion
  template:
    metadata:
      labels:
        app: xirion
    spec:
      containers:
        - name: xirion
          image: git.0x76.dev/v/xirion.net:2
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: xirion
  namespace: websites
spec:
  selector:
    app: xirion
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xirion
  namespace: websites
spec:
  rules:
    - host: "xirion.net"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xirion
                port:
                  number: 80
