apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: umami
  namespace: olympus
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: umami
  data:
    - secretKey: HASH_SALT
      remoteRef:
        key: olympus/umami
        property: hash_salt
