apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: umami
  namespace: olympus
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: olympus-umami-replace-js@kubernetescrd
spec:
  rules:
  - host: "analytics.0x76.dev"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: umami
            port: 
              number: 80
