# This file was generated by pkgs.mastodon.updateScript.
{ fetchFromGitHub, applyPatches, patches ? [] }:
let
  version = "0e562916cce3241d98bd10f04a6aa7419700605";
in
(
  applyPatches {
    src = fetchFromGitHub {
      owner = "glitch-soc";
      repo = "mastodon";
      rev = "v${version}";
      hash = "sha256-fZH3zPEU5jnYFhLx8OKDNrvsSVT46Peu92L84Fg5YpQ=";
    };
    patches = patches ++ [];
  }) // {
  inherit version;
  yarnHash = "sha256-P7KswzsCusyiS4MxUFnC1HYMTQ6fLpIwd97AglCukIk=";
}
