# This file was generated by pkgs.mastodon.updateScript.
{ fetchgit, applyPatches }: let
  src = fetchgit {
    url = "https://github.com/glitch-soc/mastodon.git";
    rev = "ff168ef2024626f37fa776fde5739dcd58ecb9f2";
    sha256 = "16w1hzx45i2kf5jgy32v96l4zaa1zzmvda19yqckc48l0fxcn39p";
  };
in applyPatches {
  inherit src;
  patches = [];
}
