# This file was generated by pkgs.mastodon.updateScript.
{ fetchFromGitHub, applyPatches, patches ? [] }:
let
<<<<<<< HEAD
  version = "bc39b3196db8c79719c5a6c920c780284b8266a";
=======
  version = "5bc39b3";
  revision = "5bc39b3196db8c79719c5a6c920c780284b8266a";
>>>>>>> 8ec4a162da27435bf9deb68fa41bbfaf0c7d3f49
in
(
  applyPatches {
    src = fetchFromGitHub {
      owner = "glitch-soc";
      repo = "mastodon";
<<<<<<< HEAD
      rev = "v${version}";
      hash = "sha256-6ipYkF0PP3D15PD7vyN1cGqnxoBRrXEaRsrto7ZXej0=";
    };
    patches = patches ++ [];
  }) // {
  inherit version;
  yarnHash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
=======
      rev = "${revision}";
      hash = "sha256-6ipYkF0PP3D15PD7vyN1cGqnxoBRrXEaRsrto7ZXej0=";
    };
    patches = patches ++ [./yarn-typescript.patch];
  }) // {
  inherit version;
  yarnHash = "sha256-CIIz5wwWzvDKc/VbSIT7Z5D9kwOLoErXoO0WQWfV/g4=";
>>>>>>> 8ec4a162da27435bf9deb68fa41bbfaf0c7d3f49
}
