apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpa
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: vpa
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 5m
  timeout: 20m
  values:
    recommender:
      enabled: true
    updater:
      enabled: false
    admissionController:
      enabled: false
