apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: oidc-auth
  dataFrom:
    - extract:
        key: flux-system/weave-gitops
