apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: services
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: config-volume
              configMap:
                name: renovate
            - name: work-volume
              emptyDir: {}
          containers:
            - name: renovate
              image: renovate/renovate:34.113.0
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_ENDPOINT
                  value: "https://git.0x76.dev/api/v1/"
                - name: RENOVATE_PLATFORM
                  value: gitea
                - name: RENOVATE_AUTODISCOVER
                  value: "false"
                - name: RENOVATE_GIT_AUTHOR
                  value: "Renovate Bot <renovate@xirion.net>"
                - name: RENOVATE_CONFIG_FILE
                  value: "/opt/renovate/config.js"
                - name: RENOVATE_BASE_DIR
                  value: "/tmp/renovate"
              envFrom:
                - secretRef:
                    name: renovate
          restartPolicy: Never
