templates:
  Studio:
    optional:
      - company
    tmdb_company: <<company>>
    sort_title: <<collection_name>>
    sync_mode: sync
    smart_label: release.desc
  Set:
    optional:
      - collection
      - movie
      - list
      - background
      - poster
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    tmdb_list: <<list>>
    sync_mode: sync
    collection_order: release
    url_poster: <<poster>>
    sort_title: <<collection_name>>
    url_background: <<background>>
collections:
  Marvel Cinematic Universe:
    tvdb_list: https://thetvdb.com/lists/marvel-cinematic-universe
    template:
      name: Set
      poster: https://theposterdb.com/api/assets/162417
  Star Wars:
    template:
      name: Set
      collection: 10
      poster: https://theposterdb.com/api/assets/164120
  Studio Ghibli:
    template: { name: Studio, company: 10342 }
    url_poster: https://theposterdb.com/api/assets/393
  Pixar:
    template: { name: Studio, company: 3 }
    url_poster: https://theposterdb.com/api/assets/18894
  Star Trek:
    tmdb_collection:
      - 151
      - 115570
    template:
      name: Set
      poster: https://theposterdb.com/api/assets/222279
      background: https://i.imgur.com/Yp0NCZa.jpg
  Bad Trek:
    template:
      name: Set
      collection: 115575
  National Theatre:
    imdb_list: https://www.imdb.com/search/title/?companies=co0388435
    template:
      name: Studio
      company: 16355
