---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/olympus/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
