apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: polaris
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: polaris
      version: 5.4.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 5m
  timeout: 20m
  values:
    dashboard:
      replicas: 1
      enable: true
