apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
  namespace: authentik
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: authentik
  data:
  - secretKey: secret_key
    remoteRef:
      key: authentik/authentik
      property: secret_key
