apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: identity-system
spec:
  interval: 1m0s
  chart: 
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2022.4.3
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: Secret
      name: authentik
      valuesKey: secret_key
      targetPath: authentik.secret_key
      optional: false
  values:
    authentik:
      error_reporting:
        enabled: true
      postgresql:
        host: "database.olympus"
        name: "authentik"
        user: "authentik"
    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
    ingress:
      enabled: true
      ingressClassName: "traefik"
      hosts:
        - host: id.0x76.dev
          paths:
            - path: "/"
              pathType: Prefix
