apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: renovate
  namespace: gitops
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: renovate
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: gitops/renovate
        property: gitea_token
    - secretKey: GITHUB_COM_TOKEN
      remoteRef:
        key: gitops/renovate
        property: github_token
