---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-infrastructure
  namespace: gitops
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
          containers:
            - name: renovate
              image: renovate/renovate:32.66
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/
                - name: work-volume
                  mountPath: /tmp/renovate/
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_ENDPOINT
                  value: "https://git.0x76.dev/api/v1/"
                - name: RENOVATE_PLATFORM
                  value: gitea
                - name: RENOVATE_AUTODISCOVER
                  value: "false"
                - name: RENOVATE_GIT_AUTHOR
                  value: "Renovate Bot <renovate@xirion.net>"
                - name: RENOVATE_CONFIG_FILE
                  value: "/opt/renovate/config.js"
                - name: RENOVATE_BASE_DIR
                  value: "/tmp/renovate"
              envFrom:
                - secretRef:
                    name: renovate
          restartPolicy: Never
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: gitops
data:
  config.js: |-
    module.exports = {
      "repositories": ["v/infrastructure"],
      "flux": {
        "fileMatch": ["flux/.+\\.ya?ml$"]
      },
      "helm-values": {
        "fileMatch": ["flux/.+\\.ya?ml$"]
      },
      "kubernetes": {
        "fileMatch": ["flux/.+\\.ya?ml$"]
      },
      "hostRules": [
        {
          "hostType": "docker",
          "matchHost": "ghcr.io",
          "username": "NULLx76",
          "password": process.env.GITHUB_COM_TOKEN
        }
      ],
      "packageRules": [
        {
          "automerge": true,
          "automergeType": "pr",
          "matchPackageNames": [
            "renovate/renovate"
          ]
        }
      ],
      "regexManagers": [
        {
          "description": "Process GitRepository CRD dependencies - Chart and Github Release are the same version",
          "fileMatch": ["flux/cluster/crds/.+\\.ya?ml$"],
          "matchStrings": [
            "registryUrl=(?<registryUrl>\\S+) chart=(?<depName>\\S+)\n.*?(?<currentValue>[^-\\s]*)\n"
          ],
          "datasourceTemplate": "helm"
        },
        {
          "description": "Process Kustomization CRD dependencies - Image and Github Release are the same version",
          "fileMatch": ["flux/cluster/crds/.+\\.ya?ml$"],
          "matchStrings": [
            "datasource=(?<datasource>\\S+) image=(?<depName>\\S+)\n.*?-\\s(.*?)\/(?<currentValue>[^/]+)\/[^/]+\n"
          ],
          "datasourceTemplate": "docker"
        }
      ]
    };
