apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: drone
  namespace: gitops
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: drone
  data:
    - secretKey: DRONE_RPC_SECRET
      remoteRef:
        key: gitops/drone
        property: drone_rpc_secret

    - secretKey: DRONE_GITEA_CLIENT_ID
      remoteRef:
        key: gitops/drone
        property: drone_gitea_client_id

    - secretKey: DRONE_GITEA_CLIENT_SECRET
      remoteRef:
        key: gitops/drone
        property: drone_gitea_client_secret
