apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone-runner-kube
  namespace: gitops
spec:
  interval: 1h
  chart:
    spec:
      chart: drone-runner-kube
      version: 0.1.10
      sourceRef:
        kind: HelmRepository
        name: drone-charts
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: drone
      valuesKey: DRONE_RPC_SECRET
      targetPath: env.DRONE_RPC_SECRET
  values:
    image:
      repository: drone/drone-runner-kube
      tag: 1.0.0-rc.3
    rbac:
      buildNamespaces:
        - drone-build
    env:
      DRONE_NAMESPACE_DEFAULT: drone-build
