apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: gitops
spec:
  interval: 1h
  chart:
    spec:
      chart: drone
      version: 0.2.5
      sourceRef:
        kind: HelmRepository
        name: drone-charts
        namespace: flux-system
  values:
    image:
      repository: drone/drone
      tag: 2.12.1
    ingress:
      enabled: true
      hosts:
        - host: drone.0x76.dev
          paths:
            - path: /
              pathType: Prefix
    persistentVolume:
      enabled: false
    extraSecretNamesForEnvFrom:
      - drone
    env:
      DRONE_DATABASE_DRIVER: postgres
      DRONE_DATABASE_DATASOURCE: postgres://drone@10.42.42.26/drone?sslmode=disable
      DRONE_GIT_ALWAYS_AUTH: true
      DRONE_GITEA_SERVER: https://git.0x76.dev
      DRONE_SERVER_HOST: drone.0x76.dev
      DRONE_SERVER_PROTO: https
