apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: goldilocks
      version: 6.1.2
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 5m
  timeout: 20m
  values:
    dashboard:
      replicaCount: 1
      ingress:
        enabled: false
