name: NixOS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v15

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v10
        with:
          name: 0x76-infra
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Build NixOS config ❄️"
        run: |
          nix run '.#' build
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v15

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v10
        with:
          name: 0x76-infra
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: "Build NixOS config ❄️"
        run: |
          nix flake check

